api/urls.py
from django.urls import path, include
from api.views import index, merchant, shadepay
app_name = "api"
urlpatterns = [
    path('', index.index, name="index"),
    path('merchant/request', merchant.Merchant_View.as_view()),
    path('shadepay/request', shadepay.Shadepay_View.as_view())
]

shadepay/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('shadeadmin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('shadeboard/', include('shadeboard.urls')),
    path('staffboard/', include('staffboard.urls')),
    path('', include('main.urls')),   
]

staffboard/urls.py
from django.urls import path
from . import views

app_name = "staffboard"

urlpatterns = [
    path('', views.admin, name="index"),
    path('adminportal/card-requests', views.card_requests, name="card-requests"),
    path('adminportal/card-requests/<int:id>', views.card_request, name="card-request"),
    path('adminportal/card-requests/<int:id>/reference', views.card_request_reference, name="card-request-reference"),
    path('adminportal/cardless-requests', views.cardless_requests, name="cardless-requests"),
    path('adminportal/cardless-requests/<int:id>', views.cardless_request, name="cardless-request"),
    path('adminportal/cardless-requests/<int:id>/reference', views.cardless_request_reference, name="cardless-request-reference"),
    path('adminportal/recipts', views.recipts, name="recipts"),
    path('adminportal/recipts/<int:id>', views.recipt, name="recipt")
]

staffboard/models.py
from django.db import models

# Create your models here.

staffboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from main.models import BusinessWallet, DeveloperInformation, Developer, ProcessCardRequest, ProcessPayattitudeRequest, Transaction, Recipt
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse

# Create your views here.

def index(request):
    return render(request, 'staffboard/sam.html')

@login_required
def admin(request):
    loggedin_user = request.user

    if loggedin_user.is_staff:
        return render(request, "staffboard/admin/admin.html")

@login_required
def card_requests(request):
    loggedin_user = request.user

    all_requests = ProcessCardRequest.objects.all()
    all_requests = reversed(all_requests)

    if loggedin_user.is_staff:
        return render(request, "staffboard/admin/card_requests.html", {
            "all_requests": all_requests
        })

@login_required
def cardless_requests(request):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        all_requests = ProcessPayattitudeRequest.objects.all()
        all_requests = reversed(all_requests)

        return render(request, "staffboard/admin/cardless_requests.html", {
             "all_requests": all_requests
        })


@login_required
def card_request(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            transaction = ProcessCardRequest.objects.get(pk=id)
        except ProcessCardRequest.DoesNotExist:
            pass

        return render(request, "staffboard/admin/request_details.html", {
            "transaction": transaction
        })

@login_required
def cardless_request(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            transaction = ProcessPayattitudeRequest.objects.get(pk=id)
        except ProcessCardRequest.DoesNotExist:
            pass

        return render(request, "staffboard/admin/request_details.html", {
            "transaction": transaction
        })

@login_required
def recipts(request):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            recipts = Recipt.objects.all()
        except Recipt.DoesNotExist:
            pass

        recipts = reversed(recipts)

        return render(request, "staffboard/admin/recipts.html", {
            "recipts": recipts
        })

@login_required
def recipt(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            recipt = Recipt.objects.get(pk=id)
        except Recipt.DoesNotExist:
            recipt = ""

        return render(request, "staffboard/admin/recipt.html", {
            "recipt": recipt
        })

@login_required
def card_request_reference(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            transaction = ProcessCardRequest.objects.get(pk=id)
        except ProcessCardRequest.DoesNotExist:
            pass

        try:
            s_transaction = Transaction.objects.get(reference=transaction.reference)
        except Transaction.DoesNotExist:
            s_transaction = {

            }

        return render(request, "staffboard/admin/reference.html", {
            "transaction": transaction,
            "s_transaction": s_transaction
        })

@login_required
def cardless_request_reference(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            transaction = ProcessPayattitudeRequest.objects.get(pk=id)
        except ProcessCardRequest.DoesNotExist:
            pass

        try:
            s_transaction = Transaction.objects.get(reference=transaction.reference)
        except Transaction.DoesNotExist:
            s_transaction = {
                
            }

        return render(request, "staffboard/admin/reference.html", {
            "transaction": transaction,
            "s_transaction": s_transaction
        })

staffboard/templates/staffboard/admin/admin.html
{% extends "staffboard/layout.html" %}

{% block body %}
<h1>Hello Admin</h1>
{% endblock %}

staffboard/templates/staffboard/admin/card_requests.html
{% extends "staffboard/layout.html" %}
{% load static %}

{% block body %}

<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Admin portal</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Shadepay</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">admin</a></li>
                                    <li class="breadcrumb-item active">{{request.user}}</li>
                                </ol>
                            </div><!--end col-->
                        
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->


            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Transaction Requests</h4>
                        <p class="text-muted mb-0">All card <code>requests</code> and processing status. </p>
                    </div><!--end card-header-->
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered mb-0 table-centered">
                                <thead>
                                <tr>
                                    <th>Transaction ID</th>
                                    <th>User</th>
                                    <th>Reference</th>
                                    <th>Date</th>
                                    <th>Amount</th>
                                    <th>Transaction Status</th>
                                    <th class="text-right">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for r in all_requests %}
                                <tr>
                                    <td>{{r.id}}</td>
                                    <td>{{r.user}}</td>
                                    <td>{{r.reference}}</td>
                                    <td>{{r.date}}</td>
                                    <td>NGN {{r.amount}}</td>
                                    {% if r.status == "APPROVED" %}
                                    <td><span class="badge badge-soft-success">{{r.status}}</span></td>
                                    {% elif r.status == "Declined" %}
                                    <td><span class="badge badge-soft-danger">{{r.status}}</span></td>
                                    {% elif r.status == "Initiated" %}
                                    <td><span class="badge badge-soft-primary">{{r.status}}</span></td>
                                    {% else %}
                                    <td><span class="badge badge-soft-warning">{{r.status}}</span></td>
                                    {% endif %}
                                    <td class="text-right">
                                        <div class="dropdown d-inline-block">
                                            <a class="dropdown-toggle arrow-none" id="dLabel11" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                                <i class="las la-ellipsis-v font-20 text-muted"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dLabel11">
                                                <a class="dropdown-item" href="{% url 'staffboard:card-request' r.id %}">View Details</a>
                                                <a class="dropdown-item" href="#">Update Transaction</a>
                                                <a class="dropdown-item" href="{% url 'staffboard:card-request-reference' r.id %}">Reference Transaction</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}

                                </tbody>
                            </table><!--end /table-->
                        </div><!--end /tableresponsive-->
                    </div><!--end card-body-->
                </div><!--end card-->
            </div> <!-- end col -->
            </div> <!-- end row -->
    </div>
</div>
   
{% endblock %}

staffboard/templates/staffboard/admin/cardless_requests.html
{% extends "staffboard/layout.html" %}
{% load static %}

{% block body %}

<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Admin portal</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Shadepay</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">admin</a></li>
                                    <li class="breadcrumb-item active">{{request.user}}</li>
                                </ol>
                            </div><!--end col-->
                        
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->


            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Cardless Transaction Requests</h4>
                        <p class="text-muted mb-0">All cardless <code>requests</code> and processing status. </p>
                    </div><!--end card-header-->
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered mb-0 table-centered">
                                <thead>
                                <tr>
                                    <th>Transaction ID</th>
                                    <th>User</th>
                                    <th>Mobile</th>
                                    <th>Reference</th>
                                    <th>Date</th>
                                    <th>Amount</th>
                                    <th>Transaction Status</th>
                                    <th class="text-right">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for r in all_requests %}
                                <tr>
                                    <td>{{r.id}}</td>
                                    <td>{{r.user}}</td>
                                    <td>{{r.mobile}}</td>
                                    <td>{{r.reference}}</td>
                                    <td>{{r.date}}</td>
                                    <td>NGN {{r.amount}}</td>
                                    {% if r.status == "APPROVED" %}
                                    <td><span class="badge badge-soft-success">{{r.status}}</span></td>
                                    {% elif r.status == "Declined" %}
                                    <td><span class="badge badge-soft-danger">{{r.status}}</span></td>
                                    {% elif r.status == "Initiated" %}
                                    <td><span class="badge badge-soft-primary">{{r.status}}</span></td>
                                    {% else %}
                                    <td><span class="badge badge-soft-warning">{{r.status}}</span></td>
                                    {% endif %}
                                    <td class="text-right">
                                        <div class="dropdown d-inline-block">
                                            <a class="dropdown-toggle arrow-none" id="dLabel11" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                                <i class="las la-ellipsis-v font-20 text-muted"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dLabel11">
                                                <a class="dropdown-item" href="{% url 'staffboard:cardless-request' r.id %}">View Details</a>
                                                <a class="dropdown-item" href="">Update Transaction</a>
                                                <a class="dropdown-item" href="{% url 'staffboard:cardless-request-reference' r.id %}">Reference Transaction</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}

                                </tbody>
                            </table><!--end /table-->
                        </div><!--end /tableresponsive-->
                    </div><!--end card-body-->
                </div><!--end card-->
            </div> <!-- end col -->
            </div> <!-- end row -->
    </div>
</div>
   
{% endblock %}

staffboard/templates/staffboard/admin/recipts.html
{% extends "staffboard/layout.html" %}
{% load static %}

{% block body %}

<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Admin portal</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Shadepay</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">admin</a></li>
                                    <li class="breadcrumb-item active">{{request.user}}</li>
                                </ol>
                            </div><!--end col-->
                        
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->


            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Recipts</h4>
                        <p class="text-muted mb-0">All recipts </p>
                    </div><!--end card-header-->
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered mb-0 table-centered">
                                <thead>
                                <tr>
                                    <th>Recipt ID</th>
                                    <th>recipt for</th>
                                    <th>reference</th>
                                    <th>transaction id</th>
                                    <th>Amount</th>
                                    <th>Transaction Status</th>
                                    <th class="text-right">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for r in recipts %}
                                <tr>
                                    <td>{{r.id}}</td>
                                    <td>{{r.email_for}}</td>
                                    <td>{{r.trx_ref}}</td>
                                    <td>{{r.trx_id}}</td>
                                    <td>NGN {{r.amount}}</td>
                                    {% if r.status == "APPROVED" %}
                                    <td><span class="badge badge-soft-success">{{r.status}}</span></td>
                                    {% elif r.status == "Declined" %}
                                    <td><span class="badge badge-soft-danger">{{r.status}}</span></td>
                                    {% elif r.status == "Initiated" %}
                                    <td><span class="badge badge-soft-primary">{{r.status}}</span></td>
                                    {% else %}
                                    <td><span class="badge badge-soft-warning">{{r.status}}</span></td>
                                    {% endif %}
                                    <td class="text-right">
                                        <div class="dropdown d-inline-block">
                                            <a class="dropdown-toggle arrow-none" id="dLabel11" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                                <i class="las la-ellipsis-v font-20 text-muted"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dLabel11">
                                                <a class="dropdown-item" href="{% url 'staffboard:recipt' r.id %}">View Details</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}

                                </tbody>
                            </table><!--end /table-->
                        </div><!--end /tableresponsive-->
                    </div><!--end card-body-->
                </div><!--end card-->
            </div> <!-- end col -->
            </div> <!-- end row -->
    </div>
</div>
   
{% endblock %}

staffboard/templates/staffboard/admin/request_details.html
{% extends "staffboard/layout.html" %}
{% block body %}


<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Admin portal</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Shadepay</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">admin</a></li>
                                    <li class="breadcrumb-item active">{{request.user}}</li>
                                </ol>
                            </div><!--end col-->
                        
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->



            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">                                        
                            <div class="media mb-3">                                  
                                <div class="media-body align-self-center text-truncate">                                            
                                    <h4 class="m-0 font-weight-semibold text-dark font-15">Transaction Request Details</h4>   
                                    <p class="text-muted  mb-0 font-13"><span class="text-dark">User : </span>{{transaction.user}}</p>                                         
                                </div><!--end media-body-->
                            </div>   
                            <hr class="hr-dashed">
                            <div class="d-flex justify-content-between mb-3">  
                                <h6 class="font-weight-semibold m-0">Recieving Individual Wallet : <span class="text-muted font-weight-normal"> {{transaction.individual_wallet.address}}</span></h6>
                                <h6 class="font-weight-semibold m-0">Recieving Business Wallet : <span class="text-muted font-weight-normal"> {{transaction.business_wallet.address}}</span></h6>
                                <h6 class="font-weight-semibold m-0">Recieving Saving Wallet : <span class="text-muted font-weight-normal"> {{transaction.saving_wallet.address}}</span></h6>
                                <h6 class="font-weight-semibold m-0">Transaction Date : <span class="text-muted font-weight-normal"> {{transaction.date}}</span></h6>                          
                            </div> 
                            <div class="row">
                                <div class="col">
                                    <div>
                                        <h5 class="font-16 m-0 font-weight-bold">NGN {{transaction.amount}}</h5>
                                        <p class="mb-0 font-weight-semibold">Total Amount</p>                                        
                                    </div>
                                </div><!--end col-->
                                <div class="col-auto align-self-center">
                                    <h5 class="font-14 m-0 font-weight-bold">1.25% <span class="font-12 text-muted font-weight-normal">Transaction Cost</span></h5>
                                </div><!--end col-->
                            </div><!--end row-->
                            
                            <div> 
                                <p class="text-muted mt-2 mb-1">
                                </p>
                                <div class="d-flex justify-content-between">
                                    <h6 class="font-weight-semibold">Card: <span class="text-muted font-weight-normal"> {{transaction.card_first_six}} ******* {{transaction.card_last_four}}</span></h6>
                                    <h6 class="font-weight-semibold">Status : <span class="text-muted font-weight-normal"> </span>{{transaction.status}}</span></h6>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <h6 class="font-weight-semibold">Mobile: <span class="text-muted font-weight-normal"> {{transaction.mobile}}</span></h6>
                                </div>
                                <p class="text-muted text-right mb-1">{{transaction.raw_data}}</p>
                                <div class="progress mb-4" style="height: 4px;">
                                    <div class="progress-bar bg-purple" role="progressbar" style="width: 15%;" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="d-flex justify-content-between">
                                  
                                    <ul class="list-inline mb-0 align-self-center">                                                                    
                                        <li class="list-item d-inline-block mr-2">
                                            <a class="" href="#">
                                                <h6 class="font-weight-semibold">Success Record: <span class="text-muted font-weight-normal"> {{transaction.is_successful}}</span></h6>
                                            </a>
                                            <a class="" href="#">
                                                <h6 class="font-weight-semibold">Transaction Reference: <span class="text-muted font-weight-normal"> {{transaction.reference}}</span></h6>
                                            </a>
                                        </li>
                                    </ul>
                                </div>                                        
                            </div><!--end task-box-->                                                                  
                        </div><!--end card-body-->
                    </div><!--end card-->
                </div><!--end col-->
            </div>

        </div>
    </div>
{% endblock %}