api/urls.py
from django.urls import path, include
from api.views import index, merchant, shadepay
app_name = "api"
urlpatterns = [
    path('', index.index, name="index"),
    path('merchant/request', merchant.Merchant_View.as_view()),
    path('shadepay/request', shadepay.Shadepay_View.as_view())
]

main/urls.py
from django.urls import path, include
from main.views import transactions, dashboard, support, auth, index, construction, about, fees, how, contact, profile
from main.views import products, usage, privacy, terms, protection, overview, notfound, additional, wallet, news, checkout
from main.views import pay

app_name = "main"

urlpatterns = [
    path("", index.index, name="index"),
    path("about", about.about, name="about"),
    path("fees", fees.fees, name="fees"),
    path("how", how.how, name="how"),
    path("contact", contact.contact, name="contact"),
    path("privacy", privacy.privacy, name="privacy"),
    path("terms", terms.terms, name="terms"),
    path("protection", protection.protection, name="protection"),
    path("products/<str:id>", products.products_view, name="products"),
    path("usage/<str:id>", usage.usage_view, name="usage"),
    path("news", news.newsletter, name="newsletter"),
    path("overview", overview.overview, name="overview"),
    path("construction", construction.construction, name="construction"),
    path("register", auth.register, name="register"),
    path("login/", auth.login_view, name="login"),
    path("recover_password", auth.recover, name="recover"),
    path("verify/<str:uuid>/<str:token>", auth.verify, name="verify"),
    path("password-reset/<str:uuid>/<str:token>", auth.password_reset, name="password-reset"),
    path("logout", auth.logout_view, name="logout"),
    path("unverified", auth.unverified, name="unverified"),
    path("dashboard", dashboard.dashboard, name="dashboard"),
    path("profile", profile.profile_view, name="profile"),
    path("profile/deactivate", profile.deactivate_account, name="deactivate-account"),
    path("profile/update/<str:id>", profile.update_profile, name="update-profile"),
    path("pay/<str:wallet>", pay.payment_view, name="payment"),
    path("topup", transactions.topUp, name="topup"),
    path("topup/return/<int:id>", transactions.returnTopUpUrl, name="returnUrl"),
    path("transactions", transactions.transactions, name="transactions"),
    path("transactions/error", transactions.transaction_error, name="error"),
    path("transactions/success", transactions.transaction_success, name="success"),
    path("transactions/update/<int:id>/<int:rtype>", transactions.update_transaction, name="update_transaction"),
    path("request-funds", transactions.request_funds, name="request_funds"),
    path("cardless", transactions.cardless, name="cardless"),
    path("return", checkout.test, name="return-test"),
    path("cardless/return/<int:id>", transactions.returnCardlessUrl, name="cardlessReturn"),
    path("send", transactions.send, name="send"),
    path("merchant/c/checkout/<int:id>", checkout.card_checkout, name="card_checkout"),
    path("merchant/s/checkout/<int:id>", checkout.shadepay_checkout, name="shadepay_checkout"),
    path("merchant/s/checkout/<int:id>/confirm-shadepayment", checkout.confirm_shadepayment, name="confirm-shadepayment"),
    path("additional_information", additional.additional_information, name="additional_information"),
    path("wallet/create", wallet.create_business_wallet, name="new-wallet"),
    path("wallet/create/business", wallet.create_business_wallet, name="create-business-wallet"),
    path("input-validator", support.input_validator, name="input-validator"),
    path("transaction_details/<int:id>", support.transaction_details, name="transaction_details"),
    path("wallet/name/<int:wallet_type>", support.wallet_name, name="wallet_name"),
    path("<str:notfound>", notfound.notfound, name="notfound")
]

shadepay/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('shadeadmin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('shadeboard/', include('shadeboard.urls')),
    path('staffboard/', include('staffboard.urls')),
    path('', include('main.urls')),   
]

staffboard/urls.py
from django.urls import path
from . import views

app_name = "staffboard"

urlpatterns = [
    path('', views.admin, name="index"),
    path('adminportal/card-requests', views.card_requests, name="card-requests"),
    path('adminportal/card-requests/<int:id>', views.card_request, name="card-request"),
    path('adminportal/card-requests/<int:id>/reference', views.card_request_reference, name="card-request-reference"),
    path('adminportal/cardless-requests', views.cardless_requests, name="cardless-requests"),
    path('adminportal/cardless-requests/<int:id>', views.cardless_request, name="cardless-request"),
    path('adminportal/cardless-requests/<int:id>/reference', views.cardless_request_reference, name="cardless-request-reference"),
    path('adminportal/recipts', views.recipts, name="recipts"),
    path('adminportal/recipts/<int:id>', views.recipt, name="recipt")
]

staffboard/models.py
from django.db import models

# Create your models here.

staffboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from main.models import BusinessWallet, DeveloperInformation, Developer, ProcessCardRequest, ProcessPayattitudeRequest, Transaction, Recipt
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse

# Create your views here.

def index(request):
    return render(request, 'staffboard/sam.html')

@login_required
def admin(request):
    loggedin_user = request.user

    if loggedin_user.is_staff:
        return render(request, "staffboard/admin/admin.html")

@login_required
def card_requests(request):
    loggedin_user = request.user

    all_requests = ProcessCardRequest.objects.all()
    all_requests = reversed(all_requests)

    if loggedin_user.is_staff:
        return render(request, "staffboard/admin/card_requests.html", {
            "all_requests": all_requests
        })

@login_required
def cardless_requests(request):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        all_requests = ProcessPayattitudeRequest.objects.all()
        all_requests = reversed(all_requests)

        return render(request, "staffboard/admin/cardless_requests.html", {
             "all_requests": all_requests
        })


@login_required
def card_request(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            transaction = ProcessCardRequest.objects.get(pk=id)
        except ProcessCardRequest.DoesNotExist:
            pass

        return render(request, "staffboard/admin/request_details.html", {
            "transaction": transaction
        })

@login_required
def cardless_request(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            transaction = ProcessPayattitudeRequest.objects.get(pk=id)
        except ProcessCardRequest.DoesNotExist:
            pass

        return render(request, "staffboard/admin/request_details.html", {
            "transaction": transaction
        })

@login_required
def recipts(request):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            recipts = Recipt.objects.all()
        except Recipt.DoesNotExist:
            pass

        recipts = reversed(recipts)

        return render(request, "staffboard/admin/recipts.html", {
            "recipts": recipts
        })

@login_required
def recipt(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            recipt = Recipt.objects.get(pk=id)
        except Recipt.DoesNotExist:
            recipt = ""

        return render(request, "staffboard/admin/recipt.html", {
            "recipt": recipt
        })

@login_required
def card_request_reference(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            transaction = ProcessCardRequest.objects.get(pk=id)
        except ProcessCardRequest.DoesNotExist:
            pass

        try:
            s_transaction = Transaction.objects.get(reference=transaction.reference)
        except Transaction.DoesNotExist:
            s_transaction = {

            }

        return render(request, "staffboard/admin/reference.html", {
            "transaction": transaction,
            "s_transaction": s_transaction
        })

@login_required
def cardless_request_reference(request, id):
    loggedin_user = request.user

    if loggedin_user.is_staff:

        try:
            transaction = ProcessPayattitudeRequest.objects.get(pk=id)
        except ProcessCardRequest.DoesNotExist:
            pass

        try:
            s_transaction = Transaction.objects.get(reference=transaction.reference)
        except Transaction.DoesNotExist:
            s_transaction = {
                
            }

        return render(request, "staffboard/admin/reference.html", {
            "transaction": transaction,
            "s_transaction": s_transaction
        })

staffboard/templates/staffboard/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>Shadepay - Business Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static '/staffboard/assets/images/favicon.ico' %}">

        <!-- App css -->
        <link href="{% static '/staffboard/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static '/staffboard/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static '/staffboard/assets/css/metisMenu.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static '/staffboard/assets/plugins/daterangepicker/daterangepicker.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static '/staffboard/assets/css/app.min.css' %}" rel="stylesheet" type="text/css" />

    </head>

    <body>
        <!-- Left Sidenav -->
        <div class="left-sidenav">
            <!-- LOGO -->
            <div class="brand">
                <a href="{% url 'main:index' %}" class="logo">
                    <span>
                        <img style="width: 70%; height: 55%;" src="{% static '/staffboard/assets/images/logo-dark.png' %}" alt="logo-large" class="logo-lg logo-dark">
                    </span>
                </a>
            </div>
            <!--end logo-->
      
            <div class="menu-content h-100" data-simplebar>
                <ul class="metismenu left-sidenav-menu">
                    <li class="menu-label mt-0">Admin</li>
                    <li>
                        <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Transaction Requests</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li class="nav-item"><a class="nav-link" href="{% url 'staffboard:card-requests' %}"><i class="ti-control-record"></i>Card Requests</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'staffboard:cardless-requests' %}"><i class="ti-control-record"></i>Cardless Requests</a></li>
                        </ul>
                    </li>    

                    <li>
                        <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Transaction Recipts</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li class="nav-item"><a class="nav-link" href="{% url 'staffboard:recipts' %}"><i class="ti-control-record"></i>Recipts</a></li>
                        </ul>
                    </li> 
                </ul>

                <hr>

            </div>

        </div>
        <!-- end left-sidenav-->
        

        <div class="page-wrapper">
            <!-- Top Bar Start -->
            <div class="topbar">            
                <!-- Navbar -->
                <nav class="navbar-custom">    
                    <ul class="list-unstyled topbar-nav float-right mb-0">  
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button"
                                aria-haspopup="false" aria-expanded="false">
                                <span class="ml-1 nav-user-name hidden-sm">{{request.user}}</span>
                                <img src="{% static 'staffboard/assets/images/users/user-5.jpg' %}" alt="profile-user" class="rounded-circle thumb-xs" />                                 
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <div class="dropdown-divider mb-0"></div>
                                <a class="dropdown-item" href="{% url 'main:logout' %}"><i data-feather="power" class="align-self-center icon-xs icon-dual mr-1"></i> Logout</a>
                            </div>
                        </li>
                    </ul><!--end topbar-nav-->
        
                    <ul class="list-unstyled topbar-nav mb-0">                        
                        <li>
                            <button class="nav-link button-menu-mobile">
                                <i data-feather="menu" class="align-self-center topbar-icon"></i>
                            </button>
                        </li>                    
                    </ul>
                </nav>
                <!-- end navbar-->
            </div>
            <!-- Top Bar End -->

            <!-- Page Content-->
            
            <div class="page-content">

                {% include 'staffboard/partials/messages.html' %}
                
                {% block body%}
                {% endblock %}
                    

                <footer class="footer text-center text-sm-left">
                    Sandshade &copy; 2020 - 2021 <span class="d-none d-sm-inline-block float-right">All rights reserved Shadepay</span>
                </footer><!--end footer-->
            </div>
            <!-- end page content -->
        </div>
        <!-- end page-wrapper -->

        


        <!-- jQuery  -->
        <script src="{% static '/staffboard/assets/js/jquery.min.js' %}"></script>
        <script src="{% static '/staffboard/assets/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static '/staffboard/assets/js/metismenu.min.js' %}"></script>
        <script src="{% static '/staffboard/assets/js/waves.js' %}"></script>
        <script src="{% static '/staffboard/assets/js/feather.min.js' %}"></script>
        <script src="{% static '/staffboard/assets/js/simplebar.min.js' %}"></script>
        <script src="{% static '/staffboard/assets/js/moment.js' %}"></script>
        <script src="{% static '/staffboard/assets/plugins/daterangepicker/daterangepicker.js' %}"></script>

        <script src="{% static '/staffboard/assets/plugins/apex-charts/apexcharts.min.js' %}"></script>
        <script src="{% static '/staffboard/assets/pages/jquery.analytics_dashboard.init.js' %}"></script>
        <script src="{% static '/staffboard/assets/plugins/clipboard/clipboard.min.js' %}"></script>
        <script src="{% static '/staffboard/assets/pages/jquery.clipboard.init.js' %}"></script>

        <!-- App js -->
        <script src="{% static '/staffboard/assets/js/app.js' %}"></script>


    </body>

</html>