api/urls.py
from django.urls import path, include
from api.views import index, merchant, shadepay
app_name = "api"
urlpatterns = [
    path('', index.index, name="index"),
    path('merchant/request', merchant.Merchant_View.as_view()),
    path('shadepay/request', shadepay.Shadepay_View.as_view())
]

main/urls.py
from django.urls import path, include
from main.views import transactions, dashboard, support, auth, index, construction, about, fees, how, contact, profile
from main.views import products, usage, privacy, terms, protection, overview, notfound, additional, wallet, news, checkout
from main.views import pay

app_name = "main"

urlpatterns = [
    path("", index.index, name="index"),
    path("about", about.about, name="about"),
    path("fees", fees.fees, name="fees"),
    path("how", how.how, name="how"),
    path("contact", contact.contact, name="contact"),
    path("privacy", privacy.privacy, name="privacy"),
    path("terms", terms.terms, name="terms"),
    path("protection", protection.protection, name="protection"),
    path("products/<str:id>", products.products_view, name="products"),
    path("usage/<str:id>", usage.usage_view, name="usage"),
    path("news", news.newsletter, name="newsletter"),
    path("overview", overview.overview, name="overview"),
    path("construction", construction.construction, name="construction"),
    path("register", auth.register, name="register"),
    path("login/", auth.login_view, name="login"),
    path("recover_password", auth.recover, name="recover"),
    path("verify/<str:uuid>/<str:token>", auth.verify, name="verify"),
    path("password-reset/<str:uuid>/<str:token>", auth.password_reset, name="password-reset"),
    path("logout", auth.logout_view, name="logout"),
    path("unverified", auth.unverified, name="unverified"),
    path("dashboard", dashboard.dashboard, name="dashboard"),
    path("profile", profile.profile_view, name="profile"),
    path("profile/deactivate", profile.deactivate_account, name="deactivate-account"),
    path("profile/update/<str:id>", profile.update_profile, name="update-profile"),
    path("pay/<str:wallet>", pay.payment_view, name="payment"),
    path("topup", transactions.topUp, name="topup"),
    path("topup/return/<int:id>", transactions.returnTopUpUrl, name="returnUrl"),
    path("transactions", transactions.transactions, name="transactions"),
    path("transactions/error", transactions.transaction_error, name="error"),
    path("transactions/success", transactions.transaction_success, name="success"),
    path("transactions/update/<int:id>/<int:rtype>", transactions.update_transaction, name="update_transaction"),
    path("request-funds", transactions.request_funds, name="request_funds"),
    path("cardless", transactions.cardless, name="cardless"),
    path("return", checkout.test, name="return-test"),
    path("cardless/return/<int:id>", transactions.returnCardlessUrl, name="cardlessReturn"),
    path("send", transactions.send, name="send"),
    path("merchant/c/checkout/<int:id>", checkout.card_checkout, name="card_checkout"),
    path("merchant/s/checkout/<int:id>", checkout.shadepay_checkout, name="shadepay_checkout"),
    path("merchant/s/checkout/<int:id>/confirm-shadepayment", checkout.confirm_shadepayment, name="confirm-shadepayment"),
    path("additional_information", additional.additional_information, name="additional_information"),
    path("wallet/create", wallet.create_business_wallet, name="new-wallet"),
    path("wallet/create/business", wallet.create_business_wallet, name="create-business-wallet"),
    path("input-validator", support.input_validator, name="input-validator"),
    path("transaction_details/<int:id>", support.transaction_details, name="transaction_details"),
    path("wallet/name/<int:wallet_type>", support.wallet_name, name="wallet_name"),
    path("<str:notfound>", notfound.notfound, name="notfound")
]

shadepay/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('shadeadmin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('shadeboard/', include('shadeboard.urls')),
    path('staffboard/', include('staffboard.urls')),
    path('', include('main.urls')),   
]

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.db import IntegrityError
from django.core.mail import EmailMessage
from django.urls import reverse
from .models import User, IndividualWallet, SavingWallet, BusinessWallet, Card, Bank, AdditionalInformation, Developer, Transaction, Logs
from .utils import email_token_generator
from django.contrib.auth import authenticate, login, logout
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.decorators import login_required
from django.core.validators import validate_email
from django.contrib.auth.tokens import PasswordResetTokenGenerator
import threading
import json
from django.views.decorators.csrf import csrf_exempt

"""
Transaction Codes
01 = Send Internal With Individual Wallet
02 = Request Internal with Individual Wallet
03 = Pay With Card
04 = Pay With Bank
05 = Deposit To Individual Wallet
06 = Deposit To Saving Wallet
07 = Deposit To Business Wallet
08 = Pay With Individual Wallet
09 = Pay With Business Wallet
10 = Withdraw From Saving Wallet
11 = Withdraw From Business Wallet
"""

"""
Transaction Status Codes
01 = Success
02 = Canceled 
03 = Refund
04 = Hold
05 = Review
"""

class EmailThread(threading.Thread):
    """
    Email Thread Class:
    This is to speed the process of sending email to users
    The thread will be used so as to not use network thread
    """

    def __init__(self, email):
        self.email = email
        threading.Thread.__init__(self)

    def run(self):
        """
        Execute the message
        """
        self.email.send(fail_silently=False)



# Create your views here.
def index(request):
    """
    Index page
    """
    return render(request, "main/index.html")

def construction(request):
    """
    Site under construction page
    """
    return render(request, "main/construction.html")

def about(request):
    """
    About us page
    """
    return render(request, "main/about.html")

def fees(request):
    """
    Fees and pricing page
    """
    return render(request, "main/fees.html")

def how(request):
    """
    How it works page
    """
    return render(request, "main/how.html")

def contact(request):
    """
    Contact page
    """
    return render(request, "main/contact.html")

def privacy(request):
    """
    Privacy policy page
    """
    return render(request, "main/privacy.html")

def terms(request):
    """
    Terms and Services Page
    """
    return render(request, "main/terms.html")

def protection(request):
    """
    Customer protection policy page
    """
    return render(request, "main/protection.html")

def overview(request):
    """
    Developer overview page
    """
    return render(request, "main/overview.html")

def notfound(request, notfound):
    """
    Error 404! page
    """
    return render(request, "main/error.html")

def register(request):
    """
    Registration module
    """
    #Handle GET request
    if request.method == "GET":
        return render(request, "main/register.html")
    
    #Handle POST request
    if request.method == "POST":

        #Collect User Data
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        email = request.POST["email"]
        username = request.POST["username"]
        password = request.POST["password"]
        re_password = request.POST["re_password"]

        #Verify User Data
        if first_name == "" or last_name == "" or email == "" or username == "" or password == "" or re_password == "":
            return render(request, "main/register.html", {
                "message": "Fields can't be empty!"
            })

        #Verify User Password
        if password != re_password:
            return render(request, "main/register.html", {
                "message": "Password did not match!"
            })

        #Verify Password Length
        if len(password) < 6:
            return render(request, "main/register.html", {
                "message": "Passowrd too short!"
            })

        #Ensure User Email Does not Exist
        if User.objects.filter(email=email).exists():

            return render(request, "main/register.html", {
                "message": "Unable to create your account. Try again later!"
            })

        elif User.objects.filter(username=username).exists():
            
            return render(request, "main/register.html", {
                "message": "Unable to create your account. Try again later!"
            })

        else:
            #Create New User
            try:
                new_user = User.objects.create_user(
                    first_name = first_name,
                    last_name = last_name,
                    username = username,
                    email = email,
                    password = password
                )
                new_user.save()
            except IntegrityError:
                return render(request, "main/register.html", {
                    "message": "Unable to create your account. Try again later!"
                })

            #Generate verification link
            uuid = urlsafe_base64_encode(force_bytes(new_user.pk))
            token = email_token_generator.make_token(new_user)
            domain = get_current_site(request).domain
            verification_link = reverse('verify', kwargs = {'uuid' : uuid, 'token' : token})
            verification_url = 'https://' + domain + verification_link

            #Send User Email Verification Mail
            subject = 'ShadePay Account Activation'
            body = 'Hello ' + new_user.username + ', Please click on the link below to verify your account.\n' + verification_url + '\n' + '\n' + '\n' + 'Thankyou for choosing ShadePay'
            sender_email = 'services@shadepay.com'
            
            new_email = EmailMessage(
                subject,
                body,
                sender_email,
                [email],
            )

            EmailThread(new_email).start()
            
            #Login User
            login(request, new_user)

            #Redirect User To Dashboard

            return HttpResponseRedirect(reverse("dashboard"))

def verify(request, uuid, token):
    """
    Email verification module
    """

    #Verify user email
    try:
        id = force_text(urlsafe_base64_decode(uuid))
        user = User.objects.get(pk=id)

        if user.is_active:
            return HttpResponseRedirect(reverse('login'))

        else:
            user.is_active = True
            user.save()

            return HttpResponseRedirect(reverse('login'))

    except User.DoesNotExist: #Will be able crash the system if it gets a different exception
        return render(request, "main/register.html", {
            "message": "User not found, register as a new user please"
        })
    

def login_view(request):
    """
    Login module
    """

    if request.method == "GET":
        return render(request, "main/login.html")

    if request.method == "POST":
        
        #Get user data
        username = request.POST["username"]
        password = request.POST["password"]

        #Verify user data
        if username == "" or password == "":

            #Return an error message if not verified
            return render(request, "main/login.html", {
                "message": "Fields can't be empty!"
            })

         #Authenticate user
        authenticated_user = authenticate(request, username=username, password=password)

        #Verify authenticated user
        if authenticated_user is not None:
            
            #login user
            login(request, authenticated_user)

            #Redirect user to dashboard
            return HttpResponseRedirect(reverse("dashboard"))

        else:

            #Return an error message if not verified
            return render(request, "main/login.html", {
                "message": "Invalid user credentials!"
            })
            
@login_required
def logout_view(request):
    """
    Logout Module
    """
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def recover(request):
    """
    Recover password page. This loads the forget.html page
    And generates a reset password and send to user email
    """
    if request.method == "GET":
        return render(request, "main/forget.html")

    if request.method == "POST":
        
        #Get user email
        email = request.POST["email"]

        #Validate email
        if not validate_email(email):
            
            #Check user existance
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                return render(request, "main/forget.html", {
                    "message": "Recovery link has been sent to your email "
                })

            #Generate verification link
            uuid = urlsafe_base64_encode(force_bytes(user.pk))
            token = PasswordResetTokenGenerator().make_token(user)
            domain = get_current_site(request).domain
            reset_link = reverse('password-reset', kwargs = {'uuid' : uuid, 'token' : token})
            reset_url = 'https://' + domain + reset_link

            #Send User Email Verification Mail
            subject = 'Password reset'
            body = 'Hello ' + user.username + '\n Please click on the link below to reset your password.\n' + reset_url + '\n' + '\n' + '\n' + 'Thankyou for choosing ShadePay'
            sender_email = 'services@shadepay.com'
            
            reset_email = EmailMessage(
                subject,
                body,
                sender_email,
                [email],
            )

            EmailThread(reset_email).start()

main/views/about.py
from django.shortcuts import render

def about(request):
    """
    About us page
    """
    return render(request, "main/about.html")

main/views/additional.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from main.models import AdditionalInformation
from django.urls import reverse
from django.contrib import messages

@login_required
def additional_information(request):

    #TODO: Add validation, and NIN verification

    loggedin_user = request.user

    if request.method ==  "GET":
        return render(request, "main/additional_information.html")

    if request.method == "POST":
        
        phone = request.POST["phone"]
        shipping = request.POST["shipping-addr"]
        state = request.POST["state"]
        country = request.POST["country"]
        agree = request.POST.get("agree")
        is_business = request.POST.get("business")

        if agree is not None:
            pass
        else:
            messages.error(request, "You have to read and agree to our terms of services, before you can get a wallet")
            return HttpResponseRedirect(reverse("main:additional_information"))

        try:
            information = AdditionalInformation.objects.get(user=loggedin_user)
            return HttpResponseRedirect(reverse("main:new-wallet"))
        except AdditionalInformation.DoesNotExist:
            information = AdditionalInformation(
                user = loggedin_user,
                accepted_terms = False if agree == None else True,
                mobile = phone,
                shipping_address = shipping,
                state = state,
                country = "Nigeria",
                is_business = False if is_business == None else True
            )
            information.save()
            return HttpResponseRedirect(reverse("main:new-wallet"))
        

main/views/construction.py
from django.shortcuts import render

def construction(request):
    """
    Site under construction page
    """
    return render(request, "main/construction.html")

main/views/fees.py
from django.shortcuts import render

def fees(request):
    """
    Fees and pricing page
    """
    return render(request, "main/fees.html")

main/views/how.py
from django.shortcuts import render

def how(request):
    """
    How it works page
    """
    return render(request, "main/how.html")

main/views/index.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponsePermanentRedirect
from main.utils import get_geol, get_client
from geopy.geocoders import Nominatim
from main.email import EmailSender

def index(request):
    """
    Index page
    """
    return render(request, "main/index.html")

main/views/notfound.py
from django.shortcuts import render

def notfound(request, notfound):
    """
    Error 404! page
    """
    return render(request, "main/error.html")

main/views/overview.py
from django.shortcuts import render

def overview(request):
    """
    Developer overview page
    """
    return render(request, "main/overview.html")

main/views/pay.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

@login_required
def payment_view(request, wallet):
    return HttpResponseRedirect(reverse('main:index'))

main/views/privacy.py
from django.shortcuts import render

def privacy(request):
    """
    Privacy policy page
    """
    return render(request, "main/privacy.html")

main/templates/main/payattitude.html
{% extends "main/layout.html" %}
{% load static %}

{% block body %}

<section class="section-padding-sm-2 blue-bg-2">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-9 col-lg-9 col-md-12 mb-20">
                <label for="fee-generate">Note</label>
                <div class="card text-white mb-3" style="max-width: 100%; background-color: #28df99;">
                    <div class="card-body">
                      <h5 id="wallet-note-title" class="card-title">Shadepay cardless topup is powered by PayAttitude</h5>
                      <p id="wallet_note" class="card-text">If you don't have a PayAttitude account, please go to <a style="color: blue;" href="https://payattitude.com/" target="_blank">payattitude site</a> to create an account, and come back to use this service </p>
                    </div>
                  </div>
                <!-- <label for="fee-generate">Note</label>
                <input type="text" id="wallet_note" readonly="readonly" value="12" id="fee-generate" required> -->
            </div>
            <div class="col-xl-9 col-lg-9 col-md-12 mb-20">
                <div class="card">
                    <div class="card-header">
                        Cardless Top Up 
                    </div>
                    
                    <div class="card-body">
                        <div class="site-form mb-30">
                            <form action="{% url 'main:cardless' %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-sm-12 mb-10">
                                        <label for="deposit-amount">Amount</label>
                                        <input type="text" name="amount" id="deposit-amount" required>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-sm-12 mb-10">
                                        <label for="deposit-currency">Wallet</label>
                                        <select name="wallet" class="custom-select" id="deposit-currency">
                                            {% if status == 0 %}
                                            {% elif status == 1 %}
                                            <option value="3">My Wallet</option>
                                            {% endif %}
                                        </select>
                                    </div>
                                    <div class="col-xl-9 col-lg-9 col-sm-12 mb-10 payattitude-input">
                                        <label for="deposit-currency">PayAttitude Mobile</label>
                                    </div>
                                    
                                    <div class="col-xl-12 col-lg-12 col-sm-12 mb-10 payattitude-input">
                                        <input type="text" name="mobile" id="fee-generate" required>
                                        <img src="{% static '/main/assets/images/payattitude/1.png' %}" alt="Topup with PayAttitude">
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-sm-12">
                                        <button type="submit" class="bttn-mid btn-fill" alt="Topup with PayAttitude" srcset="">Top Up</button>
                                        <!-- <button type="submit" class="bttn-mid btn-fill" style="background-color: white;"><img src="{% static '/main/assets/images/payattitude/1.png' %}" alt="Topup with PayAttitude" srcset=""></button> -->
                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
    </div>
</section>

{% endblock %}

main/templates/main/register.html
{% extends "main/layout.html" %}
{% load static %}

{% block body %}


    <!--breadcrumb area-->
    <section class="breadcrumb-area gradient-overlay" style="background: url('/static/main/assets/images/banner/5.jpg');">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="site-breadcrumb">
                        <h2>Register now</h2>
                    </div>
                </div>
            </div>
        </div>
    </section><!--/breadcrumb area-->

    <!--Signup Section -->
    <section class="section-padding blue-bg shaded-bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12 centered">
                    <div class="section-title cl-white">
                        <h4><span>New</span>Create account</h4>
                        {% if message %}
                            <h4>{{ message }}</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">
                    <div class="site-form mb-30">
                        <form action="{% url 'main:register' %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-xl-6 col-lg-6 col-sm-6">
                                    <input type="text" name="first_name" placeholder="First Name" required>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-sm-6">
                                    <input type="text" name="last_name" placeholder="Last Name" required>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-sm-6">
                                    <input type="email" id="email" name="email" placeholder="Email" required>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-sm-6">
                                    <input type="text" id="username" name="username" placeholder="Username" required>
                                    <p style="color: greenyellow;" id="validator-message"></p>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-sm-6">
                                    <input type="password" name="password" placeholder="Password" required>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-sm-6">
                                    <input type="password" name="re_password" placeholder="Re-Password" required>
                                </div>
                                <div class="col-xl-12 col-lg-12 col-sm-12">
                                    <button type="submit" class="bttn-mid btn-fill w-100">Register now</button>
                                </div>
                                <div class="col-xl-12 col-lg-12 col-sm-12">
                                    <div class="extra-links">
                                        <a href="{% url 'main:login' %}" class="cl-white">Login Account?</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section><!--/Signup Section-->


    <script src="{% static '/main/assets/js/page/register.js' %}"></script>
{% endblock %}

main/templates/main/reset.html
{% extends "main/layout.html" %}
{% load static %}

{% block body %}
    <!--breadcrumb area-->
    <section class="breadcrumb-area gradient-overlay" style="background: url('/static/main/assets/images/banner/5.jpg');">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="site-breadcrumb">
                        <h2>Reset Password</h2>
                    </div>
                </div>
            </div>
        </div>
    </section><!--/breadcrumb area-->

    <!--Forget Password-->
    <section class="section-padding blue-bg dots-after">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12 centered">
                    <div class="section-title cl-white">
                        <h4><span>New</span>Forget Password?</h4>
                        {% if message %}
                            <h4>{{message}}</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
                    <div class="site-form mb-30">
                        <form action="{% url 'main:password-reset' uuid token %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-xl-12 col-lg-12 col-sm-12">
                                    <input type="password" name="password" placeholder="Password" required>
                                </div>
                                <div class="col-xl-12 col-lg-12 col-sm-12">
                                    <input type="password" name="repassword" placeholder="Confirm Password" required>
                                </div>
                                <div class="col-xl-12 col-lg-12 col-sm-12">
                                    <button type="submit" class="bttn-mid btn-fill w-100">Reset password</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section><!--/Forget Password-->

{% endblock %}

main/templates/main/transaction_error.html
{% extends "main/layout.html" %}
{% load static %}


{% block body %}
 
    <!--breadcrumb area-->
    <section class="breadcrumb-area gradient-overlay" style="background: url('/static/main/assets/images/banner/5.jpg');">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="site-breadcrumb">
                        <h2>Error</h2>
                    </div>
                </div>
            </div>
        </div>
    </section><!--/breadcrumb area-->


    <!--404 Section -->
    <section class="section-padding blue-bg">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                    <div class="section-title cl-white">
                        <h2 class="mb-20">Opps! Transaction Failed</h2>
                        <p class="mb-30">An unexpected error occured while processing your transaction, please try again</p>
                        <a href="{% url 'main:dashboard' %}" class="bttn-small btn-fill">Try again</a>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 centered">
                    <img src="{% static '/main/assets/images/404.png' %}" alt="">
                </div>
            </div>
        </div>
    </section><!--/404 Section-->

{% endblock %}

main/templates/main/transaction_success.html
{% extends "main/layout.html" %}

{% block body %}
  <!--Dashboard Bottom-->  
  <section class="section-padding-sm-2 blue-bg-2">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-9 col-lg-9 col-md-12 mb-20">
                <div class="card">
                    <div class="card-header">
                        Topup
                    </div>
                    <div class="card-body">
                        <div class="sent-success">
                            <div class="icon">
                                <i class="ti-check"></i>
                            </div>
                            <h3>Topup Successfull</h3>
                            <p>You've Successfully topped money to your wallet</p>
                            <a href="{% url 'main:dashboard' %}" class="bttn-small btn-fill">Back to dashboard</a>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</section><!--Dashboard Bottom-->
{% endblock %}