api/urls.py
from django.urls import path, include
from api.views import index, merchant, shadepay
app_name = "api"
urlpatterns = [
    path('', index.index, name="index"),
    path('merchant/request', merchant.Merchant_View.as_view()),
    path('shadepay/request', shadepay.Shadepay_View.as_view())
]

main/urls.py
from django.urls import path, include
from main.views import transactions, dashboard, support, auth, index, construction, about, fees, how, contact, profile
from main.views import products, usage, privacy, terms, protection, overview, notfound, additional, wallet, news, checkout
from main.views import pay

app_name = "main"

urlpatterns = [
    path("", index.index, name="index"),
    path("about", about.about, name="about"),
    path("fees", fees.fees, name="fees"),
    path("how", how.how, name="how"),
    path("contact", contact.contact, name="contact"),
    path("privacy", privacy.privacy, name="privacy"),
    path("terms", terms.terms, name="terms"),
    path("protection", protection.protection, name="protection"),
    path("products/<str:id>", products.products_view, name="products"),
    path("usage/<str:id>", usage.usage_view, name="usage"),
    path("news", news.newsletter, name="newsletter"),
    path("overview", overview.overview, name="overview"),
    path("construction", construction.construction, name="construction"),
    path("register", auth.register, name="register"),
    path("login/", auth.login_view, name="login"),
    path("recover_password", auth.recover, name="recover"),
    path("verify/<str:uuid>/<str:token>", auth.verify, name="verify"),
    path("password-reset/<str:uuid>/<str:token>", auth.password_reset, name="password-reset"),
    path("logout", auth.logout_view, name="logout"),
    path("unverified", auth.unverified, name="unverified"),
    path("dashboard", dashboard.dashboard, name="dashboard"),
    path("profile", profile.profile_view, name="profile"),
    path("profile/deactivate", profile.deactivate_account, name="deactivate-account"),
    path("profile/update/<str:id>", profile.update_profile, name="update-profile"),
    path("pay/<str:wallet>", pay.payment_view, name="payment"),
    path("topup", transactions.topUp, name="topup"),
    path("topup/return/<int:id>", transactions.returnTopUpUrl, name="returnUrl"),
    path("transactions", transactions.transactions, name="transactions"),
    path("transactions/error", transactions.transaction_error, name="error"),
    path("transactions/success", transactions.transaction_success, name="success"),
    path("transactions/update/<int:id>/<int:rtype>", transactions.update_transaction, name="update_transaction"),
    path("request-funds", transactions.request_funds, name="request_funds"),
    path("cardless", transactions.cardless, name="cardless"),
    path("return", checkout.test, name="return-test"),
    path("cardless/return/<int:id>", transactions.returnCardlessUrl, name="cardlessReturn"),
    path("send", transactions.send, name="send"),
    path("merchant/c/checkout/<int:id>", checkout.card_checkout, name="card_checkout"),
    path("merchant/s/checkout/<int:id>", checkout.shadepay_checkout, name="shadepay_checkout"),
    path("merchant/s/checkout/<int:id>/confirm-shadepayment", checkout.confirm_shadepayment, name="confirm-shadepayment"),
    path("additional_information", additional.additional_information, name="additional_information"),
    path("wallet/create", wallet.create_business_wallet, name="new-wallet"),
    path("wallet/create/business", wallet.create_business_wallet, name="create-business-wallet"),
    path("input-validator", support.input_validator, name="input-validator"),
    path("transaction_details/<int:id>", support.transaction_details, name="transaction_details"),
    path("wallet/name/<int:wallet_type>", support.wallet_name, name="wallet_name"),
    path("<str:notfound>", notfound.notfound, name="notfound")
]

shadeboard/urls.py
from django.urls import path
from . import views
app_name = "shadeboard"
urlpatterns = [
    path('', views.index, name="index"),
    path('apidetails', views.apidetails, name="apidetails"),
    path('business-information', views.business_information, name="business-information")
]

shadepay/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('shadeadmin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('shadeboard/', include('shadeboard.urls')),
    path('staffboard/', include('staffboard.urls')),
    path('', include('main.urls')),   
]

shadeboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from main.models import BusinessWallet, DeveloperInformation, Developer, ProcessCardRequest, ProcessPayattitudeRequest, Transaction, Recipt
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse

# Create your views here.

@login_required
def index(request):
    loggedin_user = request.user 
    try:
        wallet = BusinessWallet.objects.get(user=loggedin_user)
    except:
        return render(request, "shadeboard/index.html", {
        "balance": "Please Create a wallet to see balance",
        "address": "Please Create a wallet to see wallet address",
        "business_name": "Please Create a wallet to see business name",
        "business_address": "Please Create a wallet to see business address",
        "business_contact": "Please Create a wallet to see business contact"
        })
    
    try:
        dev = Developer.objects.get(wallet=wallet)
    except Developer.DoesNotExist:
        pass

    try: 
        dev_info = DeveloperInformation.objects.get(developer=dev)
    except DeveloperInformation.DoesNotExist:
        pass

    return render(request, "shadeboard/index.html", {
        "balance": wallet.balance,
        "address": wallet.address,
        "business_name": dev_info.business_name,
        "business_address": dev_info.business_address,
        "business_contact": dev_info.business_email + " | " + dev_info.business_phone,
        "int_key": dev.api_key,
        "payment_link": wallet.link
    })

@login_required
def apidetails(request):
    loggedin_user = request.user 
    try:
        wallet = BusinessWallet.objects.get(user=loggedin_user)
    except:
        pass
    
    try:
        dev = Developer.objects.get(wallet=wallet)
    except Developer.DoesNotExist:
        pass

    try: 
        dev_info = DeveloperInformation.objects.get(developer=dev)
    except DeveloperInformation.DoesNotExist:
        pass

    return render(request, "shadeboard/apidetails.html", {
        "dev": dev
    })


@login_required
def business_information(request):
    loggedin_user = request.user

    if request.method == "GET":
        dev_info = loggedin_user.business_wallet.get().developer_wallet_details.get().developer_details.get()
        biz_status = "Registered as a business" if loggedin_user.profile.get().is_business else "Not registered as a business, you can change to business any time you wish."

        return render(request, "shadeboard/business_information.html", {
            "details": dev_info,
            "biz_status": biz_status
        })

    if request.method == "POST":

        business_name = request.POST['business_name']
        business_phone = request.POST['business_phone']
        business_email = request.POST['business_email']
        business_status = request.POST['business_status']
        business_address = request.POST['business_address']
        business_nature = request.POST['business_nature']

        if business_name == "" or business_phone == "" or business_email == "" or business_status == "" or business_address == "" or business_nature == "":
            messages.error(request, "Please fill in the information to update")
            return HttpResponseRedirect(reverse("shadeboard:business-information"))

        dev_info = loggedin_user.business_wallet.get().developer_wallet_details.get().developer_details.get()

        dev_info.business_name = business_name
        dev_info.business_phone = business_phone
        dev_info.business_address = business_address
        dev_info.business_email = business_email
        dev_info.business_nature = business_nature
        dev_info.save()

        add_info = loggedin_user.profile.get()
        add_info.is_business = True if bool(business_status) else False
        add_info.save()

        return HttpResponseRedirect(reverse("shadeboard:business-information"))

shadeboard/templates/shadeboard/apidetails.html
{% extends 'shadeboard/layout.html' %}

{% block body %}

<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Business Wallet</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Shadepay</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">shadeboard</a></li>
                                    <li class="breadcrumb-item active">{{request.user}}</li>
                                </ol>
                            </div><!--end col-->
                        
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->



            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-inline">
                        <li class="list-inline-item">
                            <h5 class="mt-0 font-14"> Use your API key to request for payments. Don't share your API key with anyone.</h5>
                        </li>
                    </ul>
                </div><!--end col-->
            </div><!--end row-->


        <div class="row">
            <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">API KEY</h4>
                    <p class="text-muted mb-0">Authorization: Bearer API KEY</p>
                </div><!--end card-header-->
                <div class="card-body">
                    <p id="clipboardParagraph" class="border p-3">
                        {{dev.secrete_key}}
                    </p>
                    <div class="mt-3">
                            <button type="button" class="btn btn-secondary btn-clipboard" data-clipboard-action="copy" data-clipboard-target="#clipboardParagraph"><i class="far fa-copy mr-2"></i>Copy</button>
                    </div>
                </div><!--end card-body-->
            </div><!--end card-->                          
        </div> <!-- end col -->


        </div>
    </div>
</div>


{% endblock %}

shadeboard/templates/shadeboard/index.html
{% extends 'shadeboard/layout.html' %}

{% block body %}

<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Shadepay Wallet</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Shadepay</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">shadeboard</a></li>
                                    <li class="breadcrumb-item active">{{request.user}}</li>
                                </ol>
                            </div><!--end col-->
                        
                        </div><!--end row-->                                                              
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->


            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-inline">
                        <li class="list-inline-item">
                            <h5 class="mt-0 font-14">Here is an overview of your shadepay wallet.</h5>
                        </li>
                    </ul>
                </div><!--end col-->
            </div><!--end row-->



            <div class="row">

                <div class="col-lg-12">
                    <div class="card team-card">
                        <div class="card-body">
                            
                            <div class="media align-items-center">                                                                                 
                                <div class="media-body ml-3 align-self-center">
                                    <h4 class="team-leader m-0">NGN {{balance}}</h4>
                                    <p class="text-muted font-12 mb-0">Wallet balance</p>                                            
                                </div>                                                                           
                            </div> 
                        </div><!--end card-body-->
                    </div><!--end card-->
                </div><!--end col-->

                <!-- <div>
                    <div class="col-lg-6">
                        <div class="card team-card">
                            <div class="card-body">
                                
                                <div class="media align-items-center">                                                                                 
                                    <div class="media-body ml-3 align-self-center">
                                        <h4 class="team-leader m-0">{{payment_link}}</h4>
                                        <p class="text-muted font-12 mb-0">My link</p>                                            
                                    </div>                                                                           
                                </div> 
                            </div>
                        </div>
                    </div>
                </div> -->
               

                <div class="col-lg-4">
                    <div class="card team-card">
                        <div class="card-body">
                            
                            <div class="media align-items-center">                                                                                 
                                <div class="media-body ml-3 align-self-center">
                                    <h4 class="team-leader m-0">Shadepay wallet</h4>
                                    <p class="text-muted font-12 mb-0">wallet type</p>                                            
                                </div>                                                                           
                            </div> 
                            <hr class="hr-dashed my-4">
                            <div class="media align-items-center">                                                                                 
                                <div class="media-body ml-3 align-self-center">
                                    <h4 class="team-leader m-0">{{address}}</h4>
                                    <p class="text-muted font-12 mb-0">Wallet address</p>                                            
                                </div>                                                                           
                            </div>                                
                           <hr class="hr-dashed my-4">
                            <div class="media align-items-center">                                                
                                <div class="media-body ml-3 align-self-center">
                                    <h4 class="team-leader m-0">NGN</h4>
                                    <p class="text-muted font-12 mb-0">Currency</p>                                            
                                </div>                                                                         
                            </div>     
                        </div><!--end card-body-->
                    </div><!--end card-->
                </div><!--end col-->

                <div class="col-lg-4">
                    <div class="card team-card">
                        <div class="card-body">
                            
                            <div class="media align-items-center">                                                                                 
                                <div class="media-body ml-3 align-self-center">
                                    <h4 class="team-leader m-0">{{business_name}}</h4>
                                    <p class="text-muted font-12 mb-0">Business name</p>                                            
                                </div>                                                                           
                            </div> 
                            <hr class="hr-dashed my-4">
                            <div class="media align-items-center">                                                                                 
                                <div class="media-body ml-3 align-self-center">
                                    <h4 class="team-leader m-0">{{business_address}}</h4>
                                    <p class="text-muted font-12 mb-0">Business physical address</p>                                            
                                </div>                                                                           
                            </div>                                
                           <hr class="hr-dashed my-4">
                            <div class="media align-items-center">                                                
                                <div class="media-body ml-3 align-self-center">
                                    <h4 class="team-leader m-0">{{business_contact}}</h4>
                                    <p class="text-muted font-12 mb-0">Business contact information</p>                                            
                                </div>                                                                         
                            </div>     
                        </div><!--end card-body-->
                    </div><!--end card-->
                </div><!--end col-->

                <div class="col-lg-4">
                    <div class="card team-card">
                        <div class="card-body">
                            
                            <div class="media align-items-center">                                                                                 
                                <div class="media-body ml-3 align-self-center">
                                    <h4 class="team-leader m-0">Integration Key</h4>
                                    <p class="text-muted font-12 mb-0">The key below is your shadepay integration key </p>                                            
                                </div>                                                                           
                            </div> 

                            <div class="card-body">
                                <p id="clipboardParagraph" class="border p-3">
                                    {{int_key}}
                                </p>
                                <div class="mt-3">
                                        <button type="button" class="btn btn-secondary btn-clipboard" data-clipboard-action="copy" data-clipboard-target="#clipboardParagraph"><i class="far fa-copy mr-2"></i>Copy</button>
                                </div>

                            </div>
                            

                        </div><!--end card-body-->
                    </div><!--end card-->
                </div><!--end col-->

                 
            </div>




    </div>
</div>



{% endblock %}

shadeboard/templates/shadeboard/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>Shadepay - Business Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static '/shadeboard/assets/images/favicon.ico' %}">

        <!-- App css -->
        <link href="{% static '/shadeboard/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static '/shadeboard/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static '/shadeboard/assets/css/metisMenu.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static '/shadeboard/assets/plugins/daterangepicker/daterangepicker.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static '/shadeboard/assets/css/app.min.css' %}" rel="stylesheet" type="text/css" />

    </head>

    <body>
        <!-- Left Sidenav -->
        <div class="left-sidenav">
            <!-- LOGO -->
            <div class="brand">
                <a href="{% url 'main:index' %}" class="logo">
                    <span>
                        <img style="width: 70%; height: 55%;" src="{% static '/shadeboard/assets/images/logo-dark.png' %}" alt="logo-large" class="logo-lg logo-dark">
                    </span>
                </a>
            </div>
            <!--end logo-->
            
            <div class="menu-content h-100" data-simplebar>
                <ul class="metismenu left-sidenav-menu">
                    <li class="menu-label mt-0">Main</li>
                    <li>
                        <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Wallet Overview</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                        <ul class="nav-second-level" aria-expanded="false">
                            <li class="nav-item"><a class="nav-link" href="{% url 'shadeboard:index' %}"><i class="ti-control-record"></i>Overview</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'shadeboard:business-information' %}"><i class="ti-control-record"></i>Update Information</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'shadeboard:apidetails' %}"><i class="ti-control-record"></i>Developer Information</a></li>
                        </ul>
                    </li>  
                    
                </ul>
            </div>

        </div>
        <!-- end left-sidenav-->
        

        <div class="page-wrapper">
            <!-- Top Bar Start -->
            <div class="topbar">            
                <!-- Navbar -->
                <nav class="navbar-custom">    
                    <ul class="list-unstyled topbar-nav float-right mb-0">  
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button"
                                aria-haspopup="false" aria-expanded="false">
                                <span class="ml-1 nav-user-name hidden-sm">{{request.user}}</span>
                                <img src="{% static 'shadeboard/assets/images/users/user-5.jpg' %}" alt="profile-user" class="rounded-circle thumb-xs" />                                 
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <div class="dropdown-divider mb-0"></div>
                                <a class="dropdown-item" href="{% url 'main:logout' %}"><i data-feather="power" class="align-self-center icon-xs icon-dual mr-1"></i> Logout</a>
                            </div>
                        </li>
                    </ul><!--end topbar-nav-->
        
                    <ul class="list-unstyled topbar-nav mb-0">                        
                        <li>
                            <button class="nav-link button-menu-mobile">
                                <i data-feather="menu" class="align-self-center topbar-icon"></i>
                            </button>
                        </li>                    
                    </ul>
                </nav>
                <!-- end navbar-->
            </div>
            <!-- Top Bar End -->

            <!-- Page Content-->
            
            <div class="page-content">

                {% include 'shadeboard/partials/messages.html' %}
                
                {% block body%}
                {% endblock %}
                    

                <footer class="footer text-center text-sm-left">
                    Sandshade &copy; 2020 - 2021 <span class="d-none d-sm-inline-block float-right">All rights reserved Shadepay</span>
                </footer><!--end footer-->
            </div>
            <!-- end page content -->
        </div>
        <!-- end page-wrapper -->

        


        <!-- jQuery  -->
        <script src="{% static '/shadeboard/assets/js/jquery.min.js' %}"></script>
        <script src="{% static '/shadeboard/assets/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static '/shadeboard/assets/js/metismenu.min.js' %}"></script>
        <script src="{% static '/shadeboard/assets/js/waves.js' %}"></script>
        <script src="{% static '/shadeboard/assets/js/feather.min.js' %}"></script>
        <script src="{% static '/shadeboard/assets/js/simplebar.min.js' %}"></script>
        <script src="{% static '/shadeboard/assets/js/moment.js' %}"></script>
        <script src="{% static '/shadeboard/assets/plugins/daterangepicker/daterangepicker.js' %}"></script>

        <script src="{% static '/shadeboard/assets/plugins/apex-charts/apexcharts.min.js' %}"></script>
        <script src="{% static '/shadeboard/assets/pages/jquery.analytics_dashboard.init.js' %}"></script>
        <script src="{% static '/shadeboard/assets/plugins/clipboard/clipboard.min.js' %}"></script>
        <script src="{% static '/shadeboard/assets/pages/jquery.clipboard.init.js' %}"></script>

        <!-- App js -->
        <script src="{% static '/shadeboard/assets/js/app.js' %}"></script>


    </body>

</html>